# Generated by Django 5.1.11 on 2025-06-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('time', models.DateTimeField(verbose_name='Publication Time')),
                ('content', models.TextField(verbose_name='Article Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Anti-Scam Article',
                'verbose_name_plural': 'Anti-Scam Articles',
                'ordering': ['-time'],
            },
        ),
    ]
