# Generated by Django 5.1.11 on 2025-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='question',
            field=models.TextField(default='', verbose_name='User Question'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Response Content'),
        ),
    ]
