# Generated by Django 5.1.11 on 2025-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_question_alter_conversation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Response Content'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
